 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/delivery_postcodes", type: :request do
  # DeliveryPostcode. As you add validations to DeliveryPostcode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeliveryPostcode.create! valid_attributes
      get delivery_postcodes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      delivery_postcode = DeliveryPostcode.create! valid_attributes
      get delivery_postcode_url(delivery_postcode)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_delivery_postcode_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      delivery_postcode = DeliveryPostcode.create! valid_attributes
      get edit_delivery_postcode_url(delivery_postcode)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeliveryPostcode" do
        expect {
          post delivery_postcodes_url, params: { delivery_postcode: valid_attributes }
        }.to change(DeliveryPostcode, :count).by(1)
      end

      it "redirects to the created delivery_postcode" do
        post delivery_postcodes_url, params: { delivery_postcode: valid_attributes }
        expect(response).to redirect_to(delivery_postcode_url(DeliveryPostcode.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeliveryPostcode" do
        expect {
          post delivery_postcodes_url, params: { delivery_postcode: invalid_attributes }
        }.to change(DeliveryPostcode, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post delivery_postcodes_url, params: { delivery_postcode: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested delivery_postcode" do
        delivery_postcode = DeliveryPostcode.create! valid_attributes
        patch delivery_postcode_url(delivery_postcode), params: { delivery_postcode: new_attributes }
        delivery_postcode.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the delivery_postcode" do
        delivery_postcode = DeliveryPostcode.create! valid_attributes
        patch delivery_postcode_url(delivery_postcode), params: { delivery_postcode: new_attributes }
        delivery_postcode.reload
        expect(response).to redirect_to(delivery_postcode_url(delivery_postcode))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        delivery_postcode = DeliveryPostcode.create! valid_attributes
        patch delivery_postcode_url(delivery_postcode), params: { delivery_postcode: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested delivery_postcode" do
      delivery_postcode = DeliveryPostcode.create! valid_attributes
      expect {
        delete delivery_postcode_url(delivery_postcode)
      }.to change(DeliveryPostcode, :count).by(-1)
    end

    it "redirects to the delivery_postcodes list" do
      delivery_postcode = DeliveryPostcode.create! valid_attributes
      delete delivery_postcode_url(delivery_postcode)
      expect(response).to redirect_to(delivery_postcodes_url)
    end
  end
end
