 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/raspberry_pi_statuses", type: :request do
  # RaspberryPiStatus. As you add validations to RaspberryPiStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RaspberryPiStatus.create! valid_attributes
      get raspberry_pi_statuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
      get raspberry_pi_status_url(raspberry_pi_status)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_raspberry_pi_status_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
      get edit_raspberry_pi_status_url(raspberry_pi_status)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RaspberryPiStatus" do
        expect {
          post raspberry_pi_statuses_url, params: { raspberry_pi_status: valid_attributes }
        }.to change(RaspberryPiStatus, :count).by(1)
      end

      it "redirects to the created raspberry_pi_status" do
        post raspberry_pi_statuses_url, params: { raspberry_pi_status: valid_attributes }
        expect(response).to redirect_to(raspberry_pi_status_url(RaspberryPiStatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RaspberryPiStatus" do
        expect {
          post raspberry_pi_statuses_url, params: { raspberry_pi_status: invalid_attributes }
        }.to change(RaspberryPiStatus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post raspberry_pi_statuses_url, params: { raspberry_pi_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested raspberry_pi_status" do
        raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
        patch raspberry_pi_status_url(raspberry_pi_status), params: { raspberry_pi_status: new_attributes }
        raspberry_pi_status.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the raspberry_pi_status" do
        raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
        patch raspberry_pi_status_url(raspberry_pi_status), params: { raspberry_pi_status: new_attributes }
        raspberry_pi_status.reload
        expect(response).to redirect_to(raspberry_pi_status_url(raspberry_pi_status))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
        patch raspberry_pi_status_url(raspberry_pi_status), params: { raspberry_pi_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested raspberry_pi_status" do
      raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
      expect {
        delete raspberry_pi_status_url(raspberry_pi_status)
      }.to change(RaspberryPiStatus, :count).by(-1)
    end

    it "redirects to the raspberry_pi_statuses list" do
      raspberry_pi_status = RaspberryPiStatus.create! valid_attributes
      delete raspberry_pi_status_url(raspberry_pi_status)
      expect(response).to redirect_to(raspberry_pi_statuses_url)
    end
  end
end
