 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/manager/opening_times", type: :request do
  # Manager::OpeningTime. As you add validations to Manager::OpeningTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Manager::OpeningTime.create! valid_attributes
      get manager_opening_times_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      opening_time = Manager::OpeningTime.create! valid_attributes
      get manager_opening_time_url(manager_opening_time)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_manager_opening_time_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      opening_time = Manager::OpeningTime.create! valid_attributes
      get edit_manager_opening_time_url(manager_opening_time)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Manager::OpeningTime" do
        expect {
          post manager_opening_times_url, params: { manager_opening_time: valid_attributes }
        }.to change(Manager::OpeningTime, :count).by(1)
      end

      it "redirects to the created manager_opening_time" do
        post manager_opening_times_url, params: { manager_opening_time: valid_attributes }
        expect(response).to redirect_to(manager_opening_time_url(@manager_opening_time))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Manager::OpeningTime" do
        expect {
          post manager_opening_times_url, params: { manager_opening_time: invalid_attributes }
        }.to change(Manager::OpeningTime, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post manager_opening_times_url, params: { manager_opening_time: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manager_opening_time" do
        opening_time = Manager::OpeningTime.create! valid_attributes
        patch manager_opening_time_url(manager_opening_time), params: { manager_opening_time: new_attributes }
        opening_time.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the manager_opening_time" do
        opening_time = Manager::OpeningTime.create! valid_attributes
        patch manager_opening_time_url(manager_opening_time), params: { manager_opening_time: new_attributes }
        opening_time.reload
        expect(response).to redirect_to(manager_opening_time_url(opening_time))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        opening_time = Manager::OpeningTime.create! valid_attributes
        patch manager_opening_time_url(manager_opening_time), params: { manager_opening_time: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested manager_opening_time" do
      opening_time = Manager::OpeningTime.create! valid_attributes
      expect {
        delete manager_opening_time_url(manager_opening_time)
      }.to change(Manager::OpeningTime, :count).by(-1)
    end

    it "redirects to the manager_opening_times list" do
      opening_time = Manager::OpeningTime.create! valid_attributes
      delete manager_opening_time_url(manager_opening_time)
      expect(response).to redirect_to(manager_opening_times_url)
    end
  end
end
